### ISSUE TITLE
OLED module

### ISSUE THREAD

**Issue by madmalkav** [dtimber/mt32-pi-for-MiSTer#1]
Thanks for your design!

I wanted to ask which OLED module did you use for this project.

**Comment by dtimber** [comment]
Hi, thanks for your interest in the project.

I've used an 0.96" OLED with SSD1306 controller and 128x64 pixel.

I've bought mine from Amazon but you can also get them from eBay or Aliexpress:

[https://amzn.eu/d/hpo3A8o](url)

Greetings d.ti

**Comment by madmalkav** [comment]
Thanks a lot!
